### ISSUE TITLE
MalformedJsonException: Unterminated string at line 1 column 17

### ISSUE THREAD

**Issue by HyperPlay** [blablubbabc/IndividualSigns#1]
Nothing happens to the sign in game, IndividualSigns seems to not be doing anything to the signs, but I am getting this log error: http://hastebin.com/omajinijax.coffee.

My plugin's code (which is using the IndividualSigns API): http://hastebin.com/uyahinahax.avrasm

**Comment by blablubbabc** [comment]
Since MC 1.8 modifying sign packets has become more difficulty: Minecraft sends the sign text in json format now.

So if you want to modify the sign packet, via IndividualSigns API, you currently have to set the sign content to valid json.

Replacing non-json formatted parts of the line content works fine, however by doing:
event.setLine(i, line.substring(0, 16));
You are basically truncating part of the json formatted line content, resulting in the error you see in the log..

So simply remove the .substring(0, 16) part of code and it should work.

**Comment by HyperPlay** [comment]
I have changed my code to this: http://hastebin.com/opomurekun.avrasm.

Nothing happens and there are no errors, the Listener is registered as other EventHandling methods are working.

**Comment by blablubbabc** [comment]
```
for (int i = 0; i < 4; i++) {
    event.setLine(i, event.getLine(i).replace("<player>", event.getPlayer().getName()));
}
```

This should work.

However:

```
if (event.getLine(0).equals(ChatColor.DARK_BLUE + "[Market]")) {
    event.setLine(2, "");
    event.setLine(3, "");
}
```

This will not work, because line 0 will never equal 'ChatColor.DARK_BLUE + "[Market]"', because the lines of the event are not the original sign lines, but the json formatted sign lines (just like the server sends them to the client).
So either do some testing, how the json formatted line for 'ChatColor.DARK_BLUE + [Market]' looks like (you could for example print line 0 to console, if it contains '[Market]') and then check for that instead,
OR use the location from the event to get the original sign in the world and get the original line from there.

**Comment by HyperPlay** [comment]
Got it working! Thanks.
